---

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_

:release_build:
  :output: MoMo-mainboard-bootloader.elf
  :use_assembly: TRUE

:environment:

:extension:
  :executable: .elf

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - +:src/**
  :include:
    - +:../shared/pic24/src/**
    - +:../shared/portable/**
  :support:
    - test/support

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines
    - __PIC24F16KA101__
    - UNITY_INT_WIDTH=16
    - CMOCK_MEM_INDEX_TYPE=uint16_t
    - CMOCK_MEM_PTR_AS_INT=uint16_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=8192
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :test_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -x c
      - -c
      - "${1}"
      - -o ${2}
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wall
      #- -Werror  # We can't keep this on during test becuase of a CMock pointer issue
      #- -Os
      - -mlarge-code
      - -mlarge-arrays
  :test_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - ${1}
      - -o "./build/release/TestBuild.elf"
      - -Wl,-Tlinker/p24F16KA101.gld,-Map=./build/release/TestOutput.map,--report-mem
  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :win #inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb

  :release_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -x c
      - -c
      - "${1}"
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      #- -Werror
      - -O1
      #- -g debug
      - -ffunction-sections
  :release_assembler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -c
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      - -O1
      - -Wa,--no-relax
      - -ffunction-sections
      #- -c  -omf=elf  -Wa,-MD,"build/default/production/src/util/asm_sleep.o.d",--defsym=__MPLAB_BUILD=1,-g,--no-relax
  :release_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -o ${2}
      - ${1}
      - -L../shared/pic24/build/release/
      - -lPIC24shared
      - -Wl,-T./linker/p24F16KA101.gld,-Map=./build/release/MoMo-mainboard-bootloader.map,--check-sections,--no-data-init,--handles,--isr,--fill-upper=0,--stackguard=16,--no-force-link,--smart-io,--report-mem,--gc-sections
:plugins:
  :load_paths:
    - ../../tools/ceedling/plugins
    - ../../tools/ceedling-plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - bin_to_hex
...
